using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Stories.Security.JAS;

[GenerateTypedNameReferences]
public sealed partial class JASWindow : DefaultWindow
{
    public JASWindow()
    {
        RobustXamlLoader.Load(this);

    }

}
