using Content.Client._Stories.Chat;
using Content.Shared._RMC14.CCVar;
using Content.Shared._Stories.SCCVars;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class AccessibilityTab : Control
{
    public AccessibilityTab()
    {
        RobustXamlLoader.Load(this);

        Control.AddOptionCheckBox(CCVars.ChatEnableColorName, EnableColorNameCheckBox);
        Control.AddOptionCheckBox(CCVars.AccessibilityColorblindFriendly, ColorblindFriendlyCheckBox);
        Control.AddOptionCheckBox(CCVars.ReducedMotion, ReducedMotionCheckBox);
        Control.AddOptionPercentSlider(CCVars.ChatWindowOpacity, ChatWindowOpacitySlider);
        Control.AddOptionPercentSlider(CCVars.SpeechBubbleTextOpacity, SpeechBubbleTextOpacitySlider);
        Control.AddOptionPercentSlider(CCVars.SpeechBubbleSpeakerOpacity, SpeechBubbleSpeakerOpacitySlider);
        Control.AddOptionPercentSlider(CCVars.SpeechBubbleBackgroundOpacity, SpeechBubbleBackgroundOpacitySlider);
        Control.AddOptionCheckBox(CCVars.ChatAutoFillHighlights, AutoFillHighlightsCheckBox);
        Control.AddOptionColorSlider(CCVars.ChatHighlightsColor, HighlightsColorSlider);

        // RMC14
        Control.AddOptionCheckBox(RMCCVars.RMCUseAlternateSprites, RMCUseAlternateSpritesCheckBox);
        Control.AddOptionCheckBox(RMCCVars.RMCChatSquadColorMode, RMCChatSquadColorModeCheckBox);
        var crtTheme = Control.AddOptionCheckBox(RMCCVars.RMCCrtThemeEnabled, RMCCrtThemeEnabledCheckBox);
        Control.AddOptionCheckBox(RMCCVars.RMCCrtEffectsEnabled, RMCCrtEffectsEnabledCheckBox);
        Control.AddOptionCheckBox(RMCCVars.RMCXenoAbilityPreviews, XenoAbilityPreviewsCheckBox);
        Control.AddOptionCheckBox(RMCCVars.RMCMarineEquipmentPreviews, MarineEquipmentPreviewsCheckBox);
        // RMC14

        // RMC14
        crtTheme.ImmediateValueChanged += _ => UpdateCrtEffectsDisabled();
        Control.ValuesReset += UpdateCrtEffectsDisabled;
        // RMC14

        Control.AddOptionCheckBox(CCVars.AccessibilityClientCensorNudity, CensorNudityCheckBox);

        // Stories-StreamerMode-Start
        Control.AddOptionCheckBox(SCCVars.StreamerModeEnabled, StreamerModeCheckBox);
        ChatFilterButton.OnPressed += _ =>
        {
            var window = new ChatFilterWindow();
            window.OpenCentered();
        };
        // Stories-StreamerMode-End

        Control.Initialize();
    }

    // RMC14
    private void UpdateCrtEffectsDisabled()
    {
        RMCCrtEffectsEnabledCheckBox.Disabled = ShouldDisableCrtEffects(RMCCrtThemeEnabledCheckBox.Pressed);
    }

    internal static bool ShouldDisableCrtEffects(bool themeEnabled)
    {
        return !themeEnabled;
    }
    // RMC14
}
