using System.Numerics;
using Content.Client.Message;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client._Stories.Vehicle.Attachables.UI;

[GenerateTypedNameReferences]
public sealed partial class VehicleAttachableHolderStripMenu : FancyWindow
{
    private readonly Dictionary<string, VehicleAttachableSlotControl> _attachableSlotControls;

    public VehicleAttachableHolderStripMenu()
    {
        RobustXamlLoader.Load(this);
        _attachableSlotControls = new Dictionary<string, VehicleAttachableSlotControl>();
    }

    public void UpdateMenu(Dictionary<string, (string? attachableName, bool locked, string? description, string? stats)> attachableSlots, Action<string> onPressed)
    {
        foreach (var slotId in attachableSlots.Keys)
        {
            if (!_attachableSlotControls.ContainsKey(slotId))
                AddSlotControl(slotId, onPressed);

            _attachableSlotControls[slotId].Update(
                attachableSlots[slotId].attachableName,
                attachableSlots[slotId].locked,
                attachableSlots[slotId].description,
                attachableSlots[slotId].stats);
        }
    }

    private void AddSlotControl(string slotId, Action<string> onPressed)
    {
        var slotControl = new VehicleAttachableSlotControl(slotId, onPressed);
        VehicleAttachablesContainer.AddChild(slotControl);
        _attachableSlotControls.Add(slotId, slotControl);
    }

    private sealed class VehicleAttachableSlotControl : Control
    {
        private readonly Button _attachableButton;
        private readonly Button _infoButton;
        private readonly PanelContainer _descriptionPanel;
        private readonly RichTextLabel _descriptionLabel;
        private readonly string _slotId;
        private readonly Action<string> _onPressed;
        private bool _expanded;

        public VehicleAttachableSlotControl(string slotId, Action<string> onPressed)
        {
            _slotId = slotId;
            _onPressed = onPressed;
            _expanded = false;

            var slotLabel = new Label
            {
                Text = Loc.GetString(slotId) + ':',
                HorizontalAlignment = HAlignment.Left,
                VerticalAlignment = VAlignment.Center,
                MinSize = new Vector2(120, 0)
            };

            var icon = new TextureRect
            {
//                Texture = StaticIcons.GenericGear,
                HorizontalAlignment = HAlignment.Left,
                VerticalAlignment = VAlignment.Center,
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                MaxSize = new Vector2(24, 24),
                Margin = new Thickness(5, 0, 5, 0)
            };

            _attachableButton = new Button
            {
                Text = Loc.GetString("st-vehicle-attachable-holder-strip-ui-empty-slot"),
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Stretch,
                StyleClasses = { StyleBase.ButtonOpenRight },
                VerticalAlignment = VAlignment.Center
            };

            _infoButton = new Button
            {
                Text = "ⓘ",
                StyleClasses = { StyleBase.ButtonOpenLeft },
                ToolTip = Loc.GetString("st-vehicle-attachable-holder-strip-ui-info-button-tooltip"),
                VerticalAlignment = VAlignment.Center
            };

            _descriptionLabel = new RichTextLabel
            {
                Margin = new Thickness(5, 5, 5, 5),
                MaxWidth = 380
            };

            _descriptionPanel = new PanelContainer
            {
                PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#25252A") },
                Visible = false,
                VerticalExpand = false,
                Children = { _descriptionLabel }
            };

            var buttonContainer = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Children = { _attachableButton, _infoButton }
            };

            var hBox = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                Children =
                {
                    icon,
                    slotLabel,
                    buttonContainer,
                },
                Margin = new Thickness(0, 0, 0, 5)
            };

            var vBox = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                Children =
                {
                    hBox,
                    _descriptionPanel
                }
            };

            _attachableButton.OnPressed += _ => onPressed(slotId);
            _infoButton.OnPressed += _ => ToggleDescription();

            AddChild(vBox);
        }

        private void ToggleDescription()
        {
            _expanded = !_expanded;
            _descriptionPanel.Visible = _expanded;
            _infoButton.Text = _expanded ? "▲" : "ⓘ";
        }

        public void Update(string? attachableName, bool slotLocked, string? description, string? stats)
        {
            if (attachableName == null)
            {
                _attachableButton.Text = Loc.GetString("st-ui-attachable-holder-strip-ui-empty-slot");
                _attachableButton.Disabled = true;
                _infoButton.Disabled = true;
                _descriptionPanel.Visible = false;
                _expanded = false;
                return;
            }

            _attachableButton.Text = attachableName;
            _attachableButton.Disabled = slotLocked;
            _infoButton.Disabled = false;

            var descText = "";
            if (!string.IsNullOrEmpty(description))
            {
                descText += $"[font size=12][color=#AAA]{description}[/color][/font]\n";
            }
            if (!string.IsNullOrEmpty(stats))
            {
                descText += $"\n[font size=12][color=#DDD]{stats}[/color][/font]";
            }

            _descriptionLabel.SetMarkupPermissive(descText);
        }
    }
}
