using Content.Shared._Stories.Synth.VoiceSynthesizer;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._Stories.Synth.VoiceSynthesizer;

[GenerateTypedNameReferences]
public sealed partial class STSynthVoiceSynthesizerWindow : DefaultWindow
{
    public event Action<string>? OnLinePressed;

    private bool _onCooldown;

    private System.Threading.CancellationTokenSource? _cooldownCancel;

    private readonly List<(string Id, string Text, Button SearchButton)> _allLines = new();

    public STSynthVoiceSynthesizerWindow()
    {
        RobustXamlLoader.Load(this);

        SearchBar.OnTextChanged += _ => UpdateSearch();
    }

    public void Populate(IPrototypeManager prototypes)
    {
        var byCategory = new Dictionary<string, (string Name, BoxContainer Content)>();

        foreach (var line in prototypes.EnumeratePrototypes<STSynthVoiceLinePrototype>())
        {
            var categoryName = Loc.GetString(line.Category);
            if (!byCategory.TryGetValue(categoryName, out var tab))
            {
                var content = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    VerticalExpand = true,
                };

                var scroll = new ScrollContainer
                {
                    VerticalExpand = true,
                    HorizontalExpand = true,
                };
                scroll.AddChild(content);

                var wrapper = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    VerticalExpand = true,
                };
                wrapper.AddChild(scroll);

                CategoryTabs.AddChild(wrapper);
                TabContainer.SetTabTitle(wrapper, categoryName);

                tab = (categoryName, content);
                byCategory[categoryName] = tab;
            }

            var lineText = Loc.GetString(line.Text);
            var lineId = line.ID;

            var tabButton = new Button
            {
                Text = lineText,
                HorizontalExpand = true,
                ToolTip = lineId,
            };
            tabButton.OnPressed += _ => TryPlayLine(lineId);
            tab.Content.AddChild(tabButton);

            var searchButton = new Button
            {
                Text = lineText,
                HorizontalExpand = true,
                ToolTip = lineId,
                Visible = false,
            };
            searchButton.OnPressed += _ => TryPlayLine(lineId);
            SearchResultsContainer.AddChild(searchButton);

            _allLines.Add((lineId, lineText, searchButton));
        }
    }

    public void SetTheme(bool useAlternateSound)
    {
        Title = Loc.GetString(useAlternateSound
            ? "st-hazmat-joe-voice-panel-title"
            : "st-working-joe-voice-panel-title");
    }

    private void TryPlayLine(string lineId)
    {
        if (_onCooldown)
            return;

        OnLinePressed?.Invoke(lineId);
    }

    private void UpdateSearch()
    {
        var search = SearchBar.Text.Trim();

        if (string.IsNullOrEmpty(search))
        {
            CategoryTabs.Visible = true;
            SearchResultsScroll.Visible = false;
            return;
        }

        CategoryTabs.Visible = false;
        SearchResultsScroll.Visible = true;

        foreach (var (_, text, button) in _allLines)
        {
            button.Visible = text.Contains(search, StringComparison.CurrentCultureIgnoreCase);
        }
    }

    public void SetCooldown(bool onCooldown, TimeSpan remaining)
    {
        _onCooldown = onCooldown;

        _cooldownCancel?.Cancel();
        _cooldownCancel = null;

        if (onCooldown && remaining > TimeSpan.Zero)
        {
            _cooldownCancel = new System.Threading.CancellationTokenSource();
            Timer.Spawn(remaining, () => _onCooldown = false, _cooldownCancel.Token);
        }
    }

    public override void Close()
    {
        base.Close();
        _cooldownCancel?.Cancel();
        _cooldownCancel = null;
    }
}
