using Content.Shared._Stories.TTS;
using Robust.Shared.GameStates;

namespace Content.Shared._RMC14.Megaphone;

[RegisterComponent, NetworkedComponent, AutoGenerateComponentState]
[Access(typeof(RMCMegaphoneSystem))]
public sealed partial class RMCMegaphoneComponent : Component
{
    /// <summary>
    /// Multiplier applied to the base voice range (normal voice range is 10).
    /// </summary>
    [DataField, AutoNetworkedField]
    public float VoiceRangeMultiplier = 1.5f;

    /// <summary>
    /// Stories: Linear gain multiplier applied to TTS generated by the megaphone user.
    /// </summary>
    [DataField("ttsVolumeMultiplier"), AutoNetworkedField]
    public float TTSVolumeMultiplier = 2f;

    /// <summary>
    /// Stories: Multiplier applied to TTS range. Defaults to the same range as the text broadcast.
    /// </summary>
    [DataField("ttsRangeMultiplier"), AutoNetworkedField]
    public float TTSRangeMultiplier = 1.5f;

    /// <summary>
    /// Stories: Server-side audio effects applied to TTS generated by the megaphone.
    /// </summary>
    [DataField("ttsAudioEffects"), AutoNetworkedField]
    public TTSAudioEffect TTSAudioEffects = TTSAudioEffect.Megaphone;
}
