using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Stories.Security.JAS.Views.Details;

[GenerateTypedNameReferences]
public sealed partial class JASDetailsView : Control
{
    public JASDetailsView()
    {
        RobustXamlLoader.Load(this);
    }
}
