using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Stories.Security.JAS.Views.Charges;

[GenerateTypedNameReferences]
public sealed partial class JASChargesView : Control
{
    public JASChargesView()
    {
        RobustXamlLoader.Load(this);
    }
}
