using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Stories.Security.JAS.Layouts.Main;

[GenerateTypedNameReferences]
public sealed partial class JASMainLayout : Control
{
    public JASMainLayout()
    {
        RobustXamlLoader.Load(this);
    }
}
