using Content.Client.Audio;
using Content.Shared._Stories.SCCVars;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.Options.UI.Tabs
{
    [GenerateTypedNameReferences]
    public sealed partial class TTSTab : Control
    {
        [Dependency] private readonly IConfigurationManager _cfg = default!;

        public TTSTab()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            Control.AddOptionCheckBox(SCCVars.TTSEnabledClient, TtsEnabledCheckBox);

            Control.AddOptionPercentSlider(
                SCCVars.TTSVolumeMarines,
                SliderVolumeMarines,
                scale: ContentAudioSystem.TtsMultiplier);

            Control.AddOptionPercentSlider(
                SCCVars.TTSVolumeXenos,
                SliderVolumeXenos,
                scale: ContentAudioSystem.TtsMultiplier);

            Control.AddOptionPercentSlider(
                SCCVars.TTSVolumeRadio,
                SliderVolumeRadio,
                scale: ContentAudioSystem.TtsMultiplier);

            Control.AddOptionPercentSlider(
                SCCVars.TTSVolumeOther,
                SliderVolumeOther,
                scale: ContentAudioSystem.TtsMultiplier);

            Control.Initialize();
        }
    }
}
