using System.Numerics;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Client.Stylesheets;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client._Stories.APC.UI;

[GenerateTypedNameReferences]
public sealed partial class APCAttachableHolderChooseSlotMenu : FancyWindow
{
    private readonly Dictionary<string, APCAttachableSlotControl> _attachableSlotControls;

    public APCAttachableHolderChooseSlotMenu()
    {
        RobustXamlLoader.Load(this);
        _attachableSlotControls = new Dictionary<string, APCAttachableSlotControl>();
    }

    public void UpdateMenu(List<string> attachableSlots, Action<string> onPressed)
    {
        foreach (var slotId in attachableSlots)
        {
            if (!_attachableSlotControls.ContainsKey(slotId))
                AddSlotControl(slotId, onPressed);
        }
    }

    private void AddSlotControl(string slotId, Action<string> onPressed)
    {
        var slotControl = new APCAttachableSlotControl(slotId, onPressed);
        SlotsContainer.AddChild(slotControl);
        _attachableSlotControls.Add(slotId, slotControl);
    }

    private sealed class APCAttachableSlotControl : Control
    {
        public APCAttachableSlotControl(string slotId, Action<string> onPressed)
        {
            var button = new Button 
            { 
                Text = Loc.GetString(slotId),
                StyleClasses = { StyleBase.ButtonOpenBoth },
                HorizontalExpand = true
            };
            
            var container = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 5)
            };
            
            var icon = new TextureRect
            {
//                Texture = StaticIcons.GenericGear,
                HorizontalAlignment = HAlignment.Left,
                VerticalAlignment = VAlignment.Center,
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                MaxSize = new Vector2(20, 20),
                Margin = new Thickness(5, 0, 5, 0)
            };
            
            container.AddChild(icon);
            container.AddChild(button);
            
            button.OnPressed += _ => onPressed(slotId);
            AddChild(container);
        }
    }
}