using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using System;
using System.Text.RegularExpressions;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Content.Shared.Popups;
using Robust.Client.Player;
using Content.Shared._Stories.APC.Systems;
using Content.Shared._Stories.APC;

namespace Content.Client._Stories.APC.UI;

[GenerateTypedNameReferences]
public sealed partial class APCControlWindow : DefaultWindow
{
    [Dependency] private readonly EntityManager _entManager = default!;
    [Dependency] private readonly IPlayerManager _playerManager = default!;
    private SharedPopupSystem _popup;
    private readonly SharedAPCEntitySystem _sharedAPCEntitySystem;

    public APCControlWindow(EntityUid owner)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _popup = _entManager.System<SharedPopupSystem>();
        EntityUid? player = _playerManager.LocalSession?.AttachedEntity;
        _sharedAPCEntitySystem = _entManager.System<SharedAPCEntitySystem>();

        PopupButton1.OnButtonDown += args =>
        {
            if (player != null)
                _popup.PopupClient("попап1", player);
        };

        PopupButton2.OnButtonDown += args =>
        {
            if (player != null)
            {
                _popup.PopupClient("Вы контролируете сущность", player);

                _sharedAPCEntitySystem.RequestControlAPC(owner, player.Value);
            }
        };
    }
}
// учусь делать юи
