using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using System;
using System.Text.RegularExpressions;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Content.Shared.Popups;
using Robust.Client.Player;
using Content.Shared._Stories.APC.Systems;
using Content.Shared._Stories.APC;
using Content.Shared._Stories.APC.UI;

namespace Content.Client._Stories.APC.UI;

[GenerateTypedNameReferences]
public sealed partial class APCControlWindow : DefaultWindow
{
    [Dependency] private readonly EntityManager _entManager = default!;
    [Dependency] private readonly IPlayerManager _playerManager = default!;

    public APCControlWindow(EntityUid owner)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }
}
