using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Stories.APC.UI;

[GenerateTypedNameReferences]
public sealed partial class APCSelectHardpointWindow : FancyWindow
{
    public APCSelectHardpointWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
