using System.Linq;
using Content.Client.Humanoid;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;
using Direction = Robust.Shared.Maths.Direction;

namespace Content.Client._Stories.Synth.Profile;

[GenerateTypedNameReferences]
public sealed partial class STSynthProfileEditor : Control
{
    private static readonly ProtoId<JobPrototype> SynthJobId = "RMCJobSynthetic";

    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly MarkingManager _markingManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private ColorSelectorSliders _rgbSkinColorSelector = default!;
    private EntityUid _previewDummy;
    private Direction _previewRotation = Direction.South;
    private HumanoidCharacterProfile? _profile;
    private List<string?> _generationIds = new() { null };

    public event Action<HumanoidCharacterProfile>? OnProfileChanged;

    public STSynthProfileEditor()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        RgbSkinColorContainer.AddChild(_rgbSkinColorSelector = new ColorSelectorSliders());
        _rgbSkinColorSelector.SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv;

        SynthNameEdit.OnTextChanged += args =>
        {
            MutateProfile(p => p.WithSynthName(args.Text));
        };

        GenerationButton.OnItemSelected += args =>
        {
            GenerationButton.SelectId(args.Id);
            MutateProfile(p => p.WithVariantPreference(SynthJobId, _generationIds[args.Id]));
        };

        Skin.OnValueChanged += _ => OnSkinColorChanged();
        _rgbSkinColorSelector.OnColorChanged += _ => OnSkinColorChanged();

        HairStylePicker.OnMarkingSelect += newStyle =>
        {
            MutateAppearance(a => a.WithHairStyleName(newStyle.id));
        };

        HairStylePicker.OnColorChanged += newColor =>
        {
            MutateAppearance(a => a.WithHairColor(newColor.marking.MarkingColors[0]));
        };

        HairStylePicker.OnSlotRemove += _ =>
        {
            MutateAppearance(a => a.WithHairStyleName(HairStyles.DefaultHairStyle));
            UpdateHairPickers();
        };

        FacialHairPicker.OnMarkingSelect += newStyle =>
        {
            MutateAppearance(a => a.WithFacialHairStyleName(newStyle.id));
        };

        FacialHairPicker.OnColorChanged += newColor =>
        {
            MutateAppearance(a => a.WithFacialHairColor(newColor.marking.MarkingColors[0]));
        };

        FacialHairPicker.OnSlotRemove += _ =>
        {
            MutateAppearance(a => a.WithFacialHairStyleName(HairStyles.DefaultFacialHairStyle));
            UpdateHairPickers();
        };

        EyeColorPicker.OnEyeColorPicked += newColor =>
        {
            MutateAppearance(a => a.WithEyeColor(newColor));
            Markings.CurrentEyeColor = newColor;
        };

        Markings.OnMarkingAdded += OnMarkingSetChanged;
        Markings.OnMarkingRemoved += OnMarkingSetChanged;
        Markings.OnMarkingColorChange += OnMarkingSetChanged;
        Markings.OnMarkingRankChange += OnMarkingSetChanged;

        RotateLeftButton.OnPressed += _ =>
        {
            _previewRotation = RotateDirection(_previewRotation, false);
            SpriteView.OverrideDirection = _previewRotation;
        };

        RotateRightButton.OnPressed += _ =>
        {
            _previewRotation = RotateDirection(_previewRotation, true);
            SpriteView.OverrideDirection = _previewRotation;
        };
    }

    public void SetProfile(HumanoidCharacterProfile? profile)
    {
        _profile = profile;
        SynthNameEdit.Text = profile?.SynthName ?? string.Empty;
        UpdateGenerationOptions();
        UpdateSkinColor();
        UpdateHairPickers();

        var appearance = CurrentAppearance();
        if (appearance != null)
        {
            EyeColorPicker.SetData(appearance.EyeColor);
            Markings.CurrentSkinColor = appearance.SkinColor;
            Markings.CurrentEyeColor = appearance.EyeColor;
            Markings.SetData(appearance.Markings, _profile!.Species, _profile.Sex, appearance.SkinColor, appearance.EyeColor);
        }

        UpdatePreview();
    }

    private HumanoidCharacterAppearance? CurrentAppearance()
    {
        return _profile?.SynthAppearance ?? _profile?.Appearance;
    }

    private void MutateAppearance(Func<HumanoidCharacterAppearance, HumanoidCharacterAppearance> mutator)
    {
        var current = CurrentAppearance();
        if (current == null)
            return;

        MutateProfile(p => p.WithSynthAppearance(mutator(current)));
        UpdatePreview();
    }

    private void MutateProfile(Func<HumanoidCharacterProfile, HumanoidCharacterProfile> mutator)
    {
        if (_profile == null)
            return;

        _profile = mutator(_profile);
        OnProfileChanged?.Invoke(_profile);
    }

    private void OnMarkingSetChanged(MarkingSet markings)
    {
        MutateAppearance(a => a.WithMarkings(markings.GetForwardEnumerator().ToList()));
    }

    private void UpdateGenerationOptions()
    {
        GenerationButton.Clear();
        _generationIds = new List<string?> { null };

        if (_profile == null ||
            !_prototypeManager.TryIndex(SynthJobId, out var job) ||
            job.Variants == null ||
            !job.SetVariantPreference)
        {
            GenerationButton.Disabled = true;
            return;
        }

        GenerationButton.AddItem(Loc.GetString("st-synth-profile-editor-generation-auto"));

        foreach (var (variantId, variantName) in job.Variants)
        {
            GenerationButton.AddItem(Loc.GetString(variantName));
            _generationIds.Add(variantId);
        }

        GenerationButton.Disabled = _generationIds.Count <= 2;

        var current = _profile.VariantPreferences.TryGetValue(SynthJobId, out var preferred) ? preferred : null;
        var index = _generationIds.IndexOf(current);
        GenerationButton.SelectId(index < 0 ? 0 : index);
    }

    private void OnSkinColorChanged()
    {
        if (_profile == null)
            return;

        var skin = _prototypeManager.Index<SpeciesPrototype>(_profile.Species).SkinColoration;

        Color color;
        switch (skin)
        {
            case HumanoidSkinColor.HumanToned:
                Skin.Visible = true;
                RgbSkinColorContainer.Visible = false;
                color = SkinColor.HumanSkinTone((int)Skin.Value);
                break;
            case HumanoidSkinColor.TintedHues:
                Skin.Visible = false;
                RgbSkinColorContainer.Visible = true;
                color = SkinColor.TintedHues(_rgbSkinColorSelector.Color);
                break;
            case HumanoidSkinColor.VoxFeathers:
                Skin.Visible = false;
                RgbSkinColorContainer.Visible = true;
                color = SkinColor.ClosestVoxColor(_rgbSkinColorSelector.Color);
                break;
            default:
                Skin.Visible = false;
                RgbSkinColorContainer.Visible = true;
                color = _rgbSkinColorSelector.Color;
                break;
        }

        Markings.CurrentSkinColor = color;
        MutateAppearance(a => a.WithSkinColor(color));
    }

    private void UpdateSkinColor()
    {
        var appearance = CurrentAppearance();
        if (_profile == null || appearance == null)
            return;

        var skin = _prototypeManager.Index<SpeciesPrototype>(_profile.Species).SkinColoration;

        switch (skin)
        {
            case HumanoidSkinColor.HumanToned:
                Skin.Visible = true;
                RgbSkinColorContainer.Visible = false;
                Skin.SetValueWithoutEvent(SkinColor.HumanSkinToneFromColor(appearance.SkinColor)); // Stories-SynthAppearance
                break;
            default:
                Skin.Visible = false;
                RgbSkinColorContainer.Visible = true;
                _rgbSkinColorSelector.Color = appearance.SkinColor;
                break;
        }
    }

    private void UpdateHairPickers()
    {
        var appearance = CurrentAppearance();
        if (_profile == null || appearance == null)
            return;

        var hairMarking = appearance.HairStyleId == HairStyles.DefaultHairStyle
            ? new List<Marking>()
            : new() { new(appearance.HairStyleId, new List<Color> { appearance.HairColor }) };

        var facialHairMarking = appearance.FacialHairStyleId == HairStyles.DefaultFacialHairStyle
            ? new List<Marking>()
            : new() { new(appearance.FacialHairStyleId, new List<Color> { appearance.FacialHairColor }) };

        HairStylePicker.UpdateData(hairMarking, _profile.Species, 1);
        FacialHairPicker.UpdateData(facialHairMarking, _profile.Species, 1);
    }

    private void UpdatePreview()
    {
        if (_profile == null)
            return;

        _entityManager.DeleteEntity(_previewDummy);

        var species = _prototypeManager.Index<SpeciesPrototype>(_profile.Species);
        _previewDummy = _entityManager.SpawnEntity(species.DollPrototype, MapCoordinates.Nullspace);

        var appearance = CurrentAppearance();
        if (appearance != null)
        {
            var previewProfile = _profile.WithCharacterAppearance(appearance);
            _entityManager.System<HumanoidAppearanceSystem>().LoadProfile(_previewDummy, previewProfile);
        }

        SpriteView.SetEntity(_previewDummy);
        SpriteView.OverrideDirection = _previewRotation;
    }

    private static Direction RotateDirection(Direction dir, bool clockwise)
    {
        var d = (int)dir;
        d = clockwise ? (d + 2) % 8 : (d - 2 + 8) % 8;
        return (Direction)d;
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (disposing)
            _entityManager.DeleteEntity(_previewDummy);
    }
}
