using Content.Client._RMC14.Lobby;
using Content.Client._Stories.Hunter;
using Content.Client._Stories.Players.JobWhitelist;
using Content.Client._Stories.Sponsors;
using Content.Client.LateJoin;
using Content.Shared._Stories.Hunter;
using Content.Shared._Stories.Hunter.Profiles;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Timing;

namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class JoinGameWindow : DefaultWindow
{
    [Dependency] private readonly IClientConsoleHost _console = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IUserInterfaceManager _uiManager = default!;
    [Dependency] private readonly IEntityNetworkManager _netEntManager = default!;

    private readonly HunterSystem _hunterSystem;
    private readonly SponsorsSystem _sponsorsSystem;
    private readonly JobWhitelistSystem _whitelistSystem;

    public JoinGameWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _hunterSystem = _entityManager.System<HunterSystem>();
        _sponsorsSystem = _entityManager.System<SponsorsSystem>();
        _whitelistSystem = _entityManager.System<JobWhitelistSystem>();

        JoinMarineButton.OnPressed += _ =>
        {
            new LateJoinGui().OpenCentered();
            Close();
        };

        JoinXenoButton.OnPressed += _ =>
        {
            _uiManager.GetUIController<RMCLobbyUIController>().OpenJoinXenoWindow();
            Close();
        };

        JoinHunterButton.OnPressed += _ =>
        {
            _netEntManager.SendSystemNetworkMessage(new RequestJoinHunterEvent());
            Close();
        };

        _hunterSystem.OnLobbyStateUpdated += UpdateHunterButtonState;

        _hunterSystem.RequestLobbyState();

        UpdateHunterButtonState();
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (disposing)
        {
            _hunterSystem.OnLobbyStateUpdated -= UpdateHunterButtonState;
        }
    }

    private void UpdateHunterButtonState()
    {
        bool isSponsor = false;
        if (_sponsorsSystem.TryGetInfo(out var sponsorInfo))
        {
            isSponsor = sponsorInfo.CanPlayHunter;
        }

        bool isAllowed = _hunterSystem.CanJoin(isSponsor, out var reason);

        if (isAllowed)
        {
            JoinHunterButton.Disabled = false;
            JoinHunterButton.Visible = true;
            JoinHunterButton.ToolTip = Loc.GetString("st-hunter-join-tooltip-available");
            HunterRequirementLabel.Visible = false;
        }
        else
        {
            JoinHunterButton.Disabled = true;
            JoinHunterButton.Visible = true;

            if (_hunterSystem.IsHuntRound)
            {
                var text = string.IsNullOrEmpty(reason) ? Loc.GetString("st-hunter-slots-full") : reason;
                JoinHunterButton.ToolTip = text;
                HunterRequirementLabel.Text = text;
                HunterRequirementLabel.Visible = true;
            }
            else
            {
                JoinHunterButton.ToolTip = Loc.GetString("st-hunter-not-hunting-ground");
                HunterRequirementLabel.Text = Loc.GetString("st-hunter-not-hunting-ground");
                HunterRequirementLabel.Visible = true;
            }
        }
    }
}
