using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Stories.Security.JAS.Layouts.Home;

[GenerateTypedNameReferences]
public sealed partial class JASHomeLayout : Control
{
    public JASHomeLayout()
    {
        RobustXamlLoader.Load(this);
    }
}
