- type: department
  parent: CMDepartmentBase
  id: CMAuxiliarySupport
  name: department-CMAuxiliarySupport
  description: cm-department-AuxiliarySupport-description
  color: "#C38312"
  roles:
  - CMAuxiliarySupportOfficer
  # Stories-start
  - StoriesLeadMechOperator
  - StoriesMechOperator
  # Stories-end
  - CMPilotDropship
  - CMPilotGunship
  - CMDropshipCrewChief
  - CMIntelOfficer
  - CMSeniorEnlistedAdvisor
  departmentRadio: MarineJTAC
  headOfDepartment: CMAuxiliarySupportOfficer
