using System.Linq;
using System.Text.RegularExpressions;
using Content.Client._Stories.Players.JobWhitelist;
using Content.Client._Stories.Sponsors;
using Content.Client._Stories.TTS;
using Content.Client.Humanoid;
using Content.Client.Inventory;
using Content.Client.Lobby;
using Content.Shared._RMC14.Clothing;
using Content.Shared._RMC14.NamedItems;
using Content.Shared._Stories.Hunter;
using Content.Shared._Stories.Hunter.Profiles;
using Content.Shared._Stories.SCCVars;
using Content.Shared._Stories.TTS;
using Content.Shared.Hands.Components;
using Content.Shared.Hands.EntitySystems;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Content.Shared.Preferences;
using Content.Shared.Preferences.Loadouts;
using Content.Shared.Roles;
using Content.Shared.Traits;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Containers;
using Robust.Shared.Enums;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;
using Robust.Shared.Random;
using Direction = Robust.Shared.Maths.Direction;
using Rope = Robust.Shared.Utility.Rope;

namespace Content.Client._Stories.Hunter.Profiles.UI;

[GenerateTypedNameReferences]
public sealed partial class HunterProfileEditor : Control
{
    private readonly Dictionary<string, Dictionary<string, List<EntProtoId>>> _categorizedPrototypes = new();
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private readonly ClientInventorySystem _inventory;
    [Dependency] private readonly MarkingManager _markingManager = default!;
    [Dependency] private readonly IClientPreferencesManager _prefsManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IRobustRandom _random = default!;
    private readonly SponsorsSystem _sponsorsSystem;

    private readonly Dictionary<int, bool> _statusAvailability = new();
    private readonly JobWhitelistSystem _whitelistSystem;
    private List<TTSVoicePrototype> _allVoices = new();

    private string _cachedFlavorText = "";
    private bool _isDirty;
    private EntProtoId _previewCapePrototype = "STHunterCapeFull";
    private EntityUid _previewDummy;
    private Direction _previewRotation = Direction.South;

    private HunterProfile? _profile;

    public HunterProfileEditor()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _inventory = _entityManager.System<ClientInventorySystem>();

        _whitelistSystem = _entityManager.System<JobWhitelistSystem>();
        _sponsorsSystem = _entityManager.System<SponsorsSystem>();

        InitializeControls();
        InitializeCustomizationTabs();

        if (_cfg.GetCVar(SCCVars.TTSEnabled))
        {
            TTSContainer.Visible = true;
            VoiceLabel.Visible = true;
            InitializeVoice();
        }
    }

    public event Action? OnProfileChanged;

    private void InitializeControls()
    {
        NameEdit.OnTextChanged += _ => SetDirty();

        RandomizeNameButton.OnPressed += _ => RandomizeName();
        RandomizeCharacterButton.OnPressed += _ => RandomizeFull();

        GenderButton.OnItemSelected += OnGenderSelected;
        AgeEdit.OnTextChanged += _ => SetDirty();

        FlavorTextEdit.OnTextChanged += _ =>
        {
            SetDirty();
            if (FlavorTextEdit.TextRope != null)
                _cachedFlavorText = Rope.Collapse(FlavorTextEdit.TextRope);
            else
                _cachedFlavorText = "";
        };

        StatusButton.OnItemSelected += OnStatusSelected;

        SkinColor.OnColorChanged += _ =>
        {
            if (_profile != null)
                _profile.SkinColor = SkinColor.Color;
            SetDirty();
            UpdatePreview();
        };

        SaveButton.OnPressed += _ => Save();
        ShowClothesButton.OnToggled += _ => UpdatePreview();

        RotateLeftButton.OnPressed += _ =>
        {
            _previewRotation = RotateDirection(_previewRotation, false);
            SpriteView.OverrideDirection = _previewRotation;
        };

        RotateRightButton.OnPressed += _ =>
        {
            _previewRotation = RotateDirection(_previewRotation, true);
            SpriteView.OverrideDirection = _previewRotation;
        };

        GenderButton.AddItem(
            Loc.GetString("humanoid-profile-editor-pronouns-male-text"),
            (int)Gender.Male
        );
        GenderButton.AddItem(
            Loc.GetString("humanoid-profile-editor-pronouns-female-text"),
            (int)Gender.Female
        );

        PopulateStatusButton();

        foreach (var style in Enum.GetValues<HunterSoundStyle>())
        {
            var text = Loc.GetString($"st-hunter-style-{style.ToString().ToLower()}");
            TranslatorStyleButton.AddItem(text, (int)style);
            CloakStyleButton.AddItem(text, (int)style);
        }

        TranslatorStyleButton.OnItemSelected += args =>
        {
            TranslatorStyleButton.SelectId(args.Id);
            if (_profile != null)
                _profile.TranslatorSound = (HunterSoundStyle)args.Id;
            SetDirty();
        };

        CloakStyleButton.OnItemSelected += args =>
        {
            CloakStyleButton.SelectId(args.Id);
            if (_profile != null)
                _profile.CloakSound = (HunterSoundStyle)args.Id;
            SetDirty();
        };

        CapeColorSelector.OnColorChanged += _ =>
        {
            if (_profile != null)
                _profile.CapeColor = CapeColorSelector.Color;
            SetDirty();
            UpdatePreview();
        };
    }

    private void PopulateStatusButton()
    {
        StatusButton.Clear();
        _statusAvailability.Clear();

        var canNormal = _whitelistSystem.IsWhitelisted("STHunter");
        var canCouncil = _whitelistSystem.IsWhitelisted("STHunterCouncil");
        var canLeader = _whitelistSystem.IsWhitelisted("STHunterLeader");

        if (_sponsorsSystem.TryGetInfo(out var sponsorInfo) && sponsorInfo.CanPlayHunter)
        {
            if (sponsorInfo.MaxHunterStatus >= HunterStatus.Normal)
                canNormal = true;
            if (sponsorInfo.MaxHunterStatus >= HunterStatus.Council)
                canCouncil = true;
            if (sponsorInfo.MaxHunterStatus >= HunterStatus.Leader)
                canLeader = true;
        }

        _statusAvailability[(int)HunterStatus.Normal] = canNormal;
        _statusAvailability[(int)HunterStatus.Council] = canCouncil;
        _statusAvailability[(int)HunterStatus.Leader] = canLeader;

        void AddStatusItem(HunterStatus status)
        {
            var id = (int)status;
            var isAvailable = _statusAvailability[id];

            if (!isAvailable)
                return;

            var nameKey = $"st-hunter-status-{status.ToString().ToLower()}";
            var name = Loc.GetString(nameKey);

            StatusButton.AddItem(name, id);
        }

        AddStatusItem(HunterStatus.Normal);
        AddStatusItem(HunterStatus.Council);
        AddStatusItem(HunterStatus.Leader);
    }

    private void OnStatusSelected(OptionButton.ItemSelectedEventArgs args)
    {
        if (_profile == null)
            return;

        if (_statusAvailability.TryGetValue(args.Id, out var available) && !available)
        {
            var fallbackId = (int)HunterStatus.Normal;
            if (_statusAvailability.TryGetValue((int)_profile.Status, out var currentIsAvailable) && currentIsAvailable)
                fallbackId = (int)_profile.Status;

            StatusButton.SelectId(fallbackId);
            return;
        }

        StatusButton.SelectId(args.Id);
        _profile.Status = (HunterStatus)args.Id;
        SetDirty();
    }

    private void InitializeVoice()
    {
        _allVoices = _prototypeManager
            .EnumeratePrototypes<TTSVoicePrototype>()
            .Where(v => v.RoundStart)
            .OrderBy(v => v.Name)
            .ToList();

        VoiceButton.OnItemSelected += args =>
        {
            VoiceButton.SelectId(args.Id);
            if (_profile != null && args.Id >= 0 && args.Id < _allVoices.Count)
            {
                var voiceProto = _allVoices[args.Id];
                if (voiceProto != null)
                    _profile.Voice = voiceProto.ID;
            }

            SetDirty();
        };

        VoicePlayButton.OnPressed += _ =>
        {
            if (_profile == null)
                return;
            var sys = _entityManager.System<TTSSystem>();
            sys.RequestPreviewTTS(_profile.Voice, true);
        };
    }

    private void UpdateVoiceSelection()
    {
        if (_profile == null)
            return;

        VoiceButton.Clear();
        var sex = _profile.Gender == Gender.Male ? Sex.Male : Sex.Female;
        var selectedListIndex = -1;

        for (var i = 0; i < _allVoices.Count; i++)
        {
            var v = _allVoices[i];

            if (v.Blacklist != null && v.Blacklist.Contains("Hunter"))
                continue;

            if (v.Sex == sex || v.Sex == Sex.Unsexed)
            {
                VoiceButton.AddItem(v.Name, i);
                if (v.ID == _profile.Voice)
                    selectedListIndex = i;
            }
        }

        if (selectedListIndex == -1)
        {
            for (var i = 0; i < _allVoices.Count; i++)
            {
                var v = _allVoices[i];
                var blocked = v.Blacklist != null && v.Blacklist.Contains("Hunter");
                if (!blocked && (v.Sex == sex || v.Sex == Sex.Unsexed))
                {
                    _profile.Voice = v.ID;
                    selectedListIndex = i;
                    break;
                }
            }
        }

        if (selectedListIndex != -1)
            VoiceButton.SelectId(selectedListIndex);
    }

    private Direction RotateDirection(Direction dir, bool clockwise)
    {
        var d = (int)dir;
        if (clockwise)
            d = (d + 2) % 8;
        else
            d = (d - 2 + 8) % 8;

        return (Direction)d;
    }

    private void InitializeCustomizationTabs()
    {
        EquipmentTabs.SetTabTitle(0, Loc.GetString("st-hunter-profile-editor-armor-tab"));
        EquipmentTabs.SetTabTitle(1, Loc.GetString("st-hunter-profile-editor-mask-tab"));
        EquipmentTabs.SetTabTitle(2, Loc.GetString("st-hunter-profile-editor-accessory-tab"));
        EquipmentTabs.SetTabTitle(3, Loc.GetString("st-hunter-profile-editor-greaves-tab"));
        EquipmentTabs.SetTabTitle(4, Loc.GetString("st-hunter-profile-editor-cape-tab"));
        EquipmentTabs.SetTabTitle(5, Loc.GetString("st-hunter-profile-editor-caster-tab"));
        EquipmentTabs.SetTabTitle(6, Loc.GetString("st-hunter-profile-editor-bracer-tab"));

        var quillPicker = new SingleMarkingPicker { Category = MarkingCategories.Hair };
        quillPicker.OnMarkingSelect += OnQuillSelected;
        quillPicker.OnColorChanged += _ => UpdatePreview();
        QuillsContent.AddChild(quillPicker);

        var categories = new Dictionary<string, (string[] SearchStrs, Control Tab)>
        {
            { "Armor", (new[] { "STHalfArmor" }, ArmorTab) },
            { "Mask", (new[] { "STMaskHunter", "STHelmetHunter" }, MaskTab) },
            { "Accessory", (new[] { "STHunterMaskAccessory" }, AccessoryTab) },
            { "Greaves", (new[] { "STBootsHunter", "STGreavesHunter" }, GreavesTab) },
        };

        var materialRegex = new Regex(@"(Ebony|Bronze|Silver|Crimson|Crimzon|Bone|Gold)", RegexOptions.IgnoreCase);

        foreach (var (category, (searchStrs, tab)) in categories)
        {
            _categorizedPrototypes[category] = new Dictionary<string, List<EntProtoId>>();

            var materialTabs = new TabContainer { VerticalExpand = true };
            tab.AddChild(materialTabs);

            var prototypes = _prototypeManager
                .EnumeratePrototypes<EntityPrototype>()
                .Where(p => !p.Abstract && searchStrs.Any(s => p.ID.StartsWith(s)))
                .ToList();

            foreach (var proto in prototypes)
            {
                var match = materialRegex.Match(proto.ID);
                var material = match.Success ? match.Value : "Standard";

                if (!_categorizedPrototypes[category].ContainsKey(material))
                    _categorizedPrototypes[category][material] = new List<EntProtoId>();
                _categorizedPrototypes[category][material].Add(proto.ID);
            }

            foreach (var (material, protos) in _categorizedPrototypes[category].OrderBy(kvp => kvp.Key))
            {
                var picker = new SpritePicker();
                picker.Populate(protos);
                picker.OnSelectionChanged += protoId => OnSpriteSelected(category, protoId);

                var materialTabBox = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    VerticalExpand = true,
                };
                materialTabBox.AddChild(picker);

                var matKey = $"st-hunter-material-{material.ToLowerInvariant()}";
                var locTitle = Loc.GetString(matKey);
                if (locTitle.StartsWith("st-hunter-material-"))
                    locTitle = material;

                materialTabs.AddChild(materialTabBox);
                materialTabs.SetTabTitle(materialTabs.ChildCount - 1, locTitle);
            }
        }

        _categorizedPrototypes["Caster"] = new Dictionary<string, List<EntProtoId>>();
        var casterProtos = _prototypeManager
            .EnumeratePrototypes<EntityPrototype>()
            .Where(p => !p.Abstract && p.ID.StartsWith("STBracerAttachmentPlasmaCaster"))
            .Select(p => (EntProtoId)p.ID)
            .ToList();

        _categorizedPrototypes["Caster"]["All"] = casterProtos;

        var casterPicker = new SpritePicker();
        casterPicker.Populate(casterProtos);
        casterPicker.OnSelectionChanged += protoId => OnSpriteSelected("Caster", protoId);
        CasterTab.AddChild(casterPicker);

        _categorizedPrototypes["Bracer"] = new Dictionary<string, List<EntProtoId>>();
        var bracerProtos = _prototypeManager
            .EnumeratePrototypes<EntityPrototype>()
            .Where(p => !p.Abstract && p.ID.StartsWith("STBracerHunter"))
            .Select(p => (EntProtoId)p.ID)
            .ToList();

        _categorizedPrototypes["Bracer"]["All"] = bracerProtos;

        var bracerPicker = new SpritePicker();
        bracerPicker.Populate(bracerProtos);
        bracerPicker.OnSelectionChanged += protoId => OnSpriteSelected("Bracer", protoId);
        BracerTab.AddChild(bracerPicker);

        _categorizedPrototypes["Cape"] = new Dictionary<string, List<EntProtoId>>();
        var capeProtos = _prototypeManager
            .EnumeratePrototypes<EntityPrototype>()
            .Where(p => !p.Abstract && p.ID.StartsWith("STHunterCape"))
            .Select(p => (EntProtoId)p.ID)
            .ToList();
        _categorizedPrototypes["Cape"]["All"] = capeProtos;

        var capePicker = new SpritePicker();
        capePicker.Populate(capeProtos);
        capePicker.OnSelectionChanged += protoId => OnSpriteSelected("Cape", protoId);
        CapeTab.AddChild(capePicker);
    }

    private void RandomizeName()
    {
        if (_profile == null)
            return;

        var currentDesc = _cachedFlavorText;
        _profile.Name = HumanoidCharacterProfile.GetName("STHunter", _profile.Gender);
        UpdateControls();
        FlavorTextEdit.TextRope = new Rope.Leaf(currentDesc);
        SetDirty();
    }

    private void RandomizeFull()
    {
        if (_profile == null)
            return;

        var randomProfile = HunterProfile.Random(_prototypeManager, _random);
        var name = HumanoidCharacterProfile.GetName("STHunter", randomProfile.Gender);
        var currentDesc = _cachedFlavorText;

        _profile.Name = name;
        _profile.Gender = randomProfile.Gender;
        _profile.Age = randomProfile.Age;
        _profile.ArmorPrototype = randomProfile.ArmorPrototype;
        _profile.MaskPrototype = randomProfile.MaskPrototype;
        _profile.GreavesPrototype = randomProfile.GreavesPrototype;
        _profile.CasterPrototype = randomProfile.CasterPrototype;
        _profile.BracerPrototype = randomProfile.BracerPrototype;
        _profile.HeadAccessory = randomProfile.HeadAccessory;
        _profile.SkinColor = randomProfile.SkinColor;
        _profile.Voice = randomProfile.Voice;
        _profile.TranslatorSound = randomProfile.TranslatorSound;
        _profile.CloakSound = randomProfile.CloakSound;
        _profile.CapeColor = randomProfile.CapeColor;

        UpdateControls();
        FlavorTextEdit.TextRope = new Rope.Leaf(currentDesc);

        SetDirty();
        UpdatePreview();
    }

    private void OnSpriteSelected(string category, EntProtoId protoId)
    {
        if (_profile == null)
            return;

        switch (category)
        {
            case "Armor":
                _profile.ArmorPrototype = protoId;
                break;
            case "Mask":
                _profile.MaskPrototype = protoId;
                break;
            case "Greaves":
                _profile.GreavesPrototype = protoId;
                break;
            case "Caster":
                _profile.CasterPrototype = protoId;
                break;
            case "Bracer":
                _profile.BracerPrototype = protoId;
                break;
            case "Accessory":
                _profile.HeadAccessory = protoId;
                break;
            case "Cape":
                _previewCapePrototype = protoId;
                break;
        }

        SetDirty();
        UpdatePreview();
    }

    private void OnGenderSelected(OptionButton.ItemSelectedEventArgs args)
    {
        if (_profile == null)
            return;
        GenderButton.SelectId(args.Id);
        _profile.Gender = (Gender)args.Id;

        UpdateVoiceSelection();
        SetDirty();
        UpdatePreview();
    }

    private void OnQuillSelected((int slot, string id) marking)
    {
        if (_profile == null)
            return;
        _profile.QuillMarkingId = new ProtoId<MarkingPrototype>(marking.id);
        SetDirty();
        UpdatePreview();
    }

    public void SetProfile(HunterProfile? profile)
    {
        _profile = profile?.Clone();
        PopulateStatusButton();
        UpdateControls();
        UpdatePreview();
        _isDirty = false;
        SaveButton.Disabled = true;
    }

    private void UpdateControls()
    {
        if (_profile == null)
            return;

        NameEdit.Text = _profile.Name;
        GenderButton.SelectId((int)_profile.Gender);
        AgeEdit.Text = _profile.Age.ToString();

        _cachedFlavorText = _profile.FlavorText ?? "";
        FlavorTextEdit.TextRope = new Rope.Leaf(_cachedFlavorText);

        var statusId = (int)_profile.Status;

        if (!_statusAvailability.TryGetValue(statusId, out var avail) || !avail)
        {
            statusId = (int)HunterStatus.Normal;
            _profile.Status = HunterStatus.Normal;
            SetDirty();
        }

        StatusButton.SelectId(statusId);

        SkinColor.Color = _profile.SkinColor;

        if (QuillsContent.ChildCount > 0 && QuillsContent.GetChild(0) is SingleMarkingPicker quillPicker)
        {
            var hairColors = new List<Color> { _profile.SkinColor };
            string markingId = _profile.QuillMarkingId;
            if (string.IsNullOrEmpty(markingId))
                markingId = "HunterHairStandard";

            var hairMarking = new List<Shared.Humanoid.Markings.Marking> { new(markingId, hairColors) };
            quillPicker.UpdateData(hairMarking, "STHunter", 1);
        }

        UpdateVoiceSelection();
        TranslatorStyleButton.SelectId((int)_profile.TranslatorSound);
        CloakStyleButton.SelectId((int)_profile.CloakSound);
        CapeColorSelector.Color = _profile.CapeColor;

        SetPickerSelected("Armor", _profile.ArmorPrototype);
        SetPickerSelected("Mask", _profile.MaskPrototype);
        SetPickerSelected("Greaves", _profile.GreavesPrototype);
        SetPickerSelected("Caster", _profile.CasterPrototype);
        SetPickerSelected("Bracer", _profile.BracerPrototype);
        SetPickerSelected("Accessory", _profile.HeadAccessory);
        SetPickerSelected("Cape", _previewCapePrototype);
    }

    private void SetPickerSelected(string category, EntProtoId protoId)
    {
        Control? tab = category switch
        {
            "Armor" => ArmorTab,
            "Mask" => MaskTab,
            "Greaves" => GreavesTab,
            "Caster" => CasterTab,
            "Bracer" => BracerTab,
            "Accessory" => AccessoryTab,
            "Cape" => CapeTab,
            _ => null,
        };

        if (tab == null)
            return;

        if (category == "Caster" || category == "Bracer" || category == "Cape")
        {
            if (tab.ChildCount > 0 && tab.GetChild(0) is SpritePicker picker)
                picker.SetSelected(protoId);
            return;
        }

        if (tab.ChildCount > 0 && tab.GetChild(0) is TabContainer materialTabs)
        {
            if (!_categorizedPrototypes.ContainsKey(category))
                return;

            foreach (var (material, protos) in _categorizedPrototypes[category])
            {
                if (protos.Contains(protoId))
                {
                    var sortedKeys = _categorizedPrototypes[category].Keys.OrderBy(k => k).ToList();
                    var index = sortedKeys.IndexOf(material);

                    if (index >= 0 && index < materialTabs.ChildCount)
                    {
                        materialTabs.CurrentTab = index;

                        if (
                            materialTabs.GetChild(index) is BoxContainer box
                            && box.ChildCount > 0
                            && box.GetChild(0) is SpritePicker picker
                        )
                            picker.SetSelected(protoId);
                        return;
                    }
                }
            }
        }
    }

    private void UpdatePreview()
    {
        if (_profile == null)
            return;

        _entityManager.DeleteEntity(_previewDummy);
        _previewDummy = _entityManager.SpawnEntity("STMobHunterDummy", MapCoordinates.Nullspace);

        var humanoidSystem = _entityManager.System<HumanoidAppearanceSystem>();
        var handsSystem = _entityManager.System<SharedHandsSystem>();

        var quillMarking = _profile.QuillMarkingId;
        if (!_prototypeManager.HasIndex(quillMarking))
            quillMarking = "HunterHairStandard";

        var appearance = new HumanoidCharacterAppearance(
            quillMarking,
            _profile.SkinColor,
            "NoFacialHair",
            Color.White,
            Color.Black,
            _profile.SkinColor,
            new List<Shared.Humanoid.Markings.Marking>()
        );

        var tempHumanoidProfile = new HumanoidCharacterProfile(
            _profile.Name,
            "",
            "STHunter",
            "",
            _profile.Age,
            _profile.Gender == Gender.Male ? Sex.Male : Sex.Female,
            _profile.Gender,
            appearance,
            SpawnPriorityPreference.None,
            ArmorPreference.Random,
            null,
            new Dictionary<ProtoId<JobPrototype>, JobPriority>(),
            PreferenceUnavailableMode.StayInLobby,
            new HashSet<ProtoId<AntagPrototype>>(),
            new HashSet<ProtoId<TraitPrototype>>(),
            new Dictionary<string, RoleLoadout>(),
            new SharedRMCNamedItems(),
            true,
            "",
            ""
        );

        humanoidSystem.LoadProfile(_previewDummy, tempHumanoidProfile);

        if (ShowClothesButton.Pressed)
        {
            void EquipIfValid(EntProtoId proto, string slot)
            {
                if (
                    !string.IsNullOrEmpty(proto)
                    && proto.Id != "Nothing"
                    && _prototypeManager.HasIndex<EntityPrototype>(proto)
                )
                {
                    _inventory.TryEquip(
                        _previewDummy,
                        _entityManager.SpawnEntity(proto, MapCoordinates.Nullspace),
                        slot,
                        true,
                        true
                    );
                }
            }

            EquipIfValid(_profile.BracerPrototype, "gloves");
            EquipIfValid(_profile.ArmorPrototype, "outerClothing");
            EquipIfValid(_profile.MaskPrototype, "mask");
            EquipIfValid(_profile.GreavesPrototype, "shoes");
            EquipIfValid(_previewCapePrototype, "back");

            if (_inventory.TryGetSlotEntity(_previewDummy, "mask", out var maskUid))
            {
                var containerSys = _entityManager.System<SharedContainerSystem>();
                if (
                    _entityManager.TryGetComponent<HelmetAccessoryHolderComponent>(maskUid, out var holder)
                    && containerSys.TryGetContainer(maskUid.Value, "helmet-accessory-container", out var container)
                )
                {
                    if (
                        !string.IsNullOrEmpty(_profile.HeadAccessory)
                        && _profile.HeadAccessory.Id != "Nothing"
                        && _prototypeManager.HasIndex<EntityPrototype>(_profile.HeadAccessory)
                    )
                    {
                        var accessory = _entityManager.SpawnEntity(_profile.HeadAccessory, MapCoordinates.Nullspace);
                        containerSys.Insert(accessory, container);
                    }
                }
            }

            if (_inventory.TryGetSlotEntity(_previewDummy, "back", out var capeUid))
            {
                _entityManager
                    .System<SharedAppearanceSystem>()
                    .SetData(capeUid.Value, HunterCapeVisuals.Color, _profile.CapeColor);
            }

            if (
                !string.IsNullOrEmpty(_profile.CasterPrototype)
                && _prototypeManager.HasIndex<EntityPrototype>(_profile.CasterPrototype)
            )
            {
                _entityManager.EnsureComponent<HandsComponent>(_previewDummy);
                var caster = _entityManager.SpawnEntity(_profile.CasterPrototype, MapCoordinates.Nullspace);
                if (!handsSystem.TryPickupAnyHand(_previewDummy, caster, false))
                    _entityManager.DeleteEntity(caster);
            }
        }

        SpriteView.SetEntity(_previewDummy);
        SpriteView.OverrideDirection = _previewRotation;
    }

    private void SetDirty()
    {
        _isDirty = true;
        SaveButton.Disabled = false;
    }

    private void Save()
    {
        if (_profile == null || !_isDirty)
            return;

        _profile.Name = NameEdit.Text;
        _profile.Gender = (Gender)GenderButton.SelectedId;

        if (int.TryParse(AgeEdit.Text, out var age))
            _profile.Age = Math.Clamp(age, 175, 3000);

        _profile.FlavorText = _cachedFlavorText;

        _profile.Status = (HunterStatus)StatusButton.SelectedId;
        _profile.SkinColor = SkinColor.Color;

        _prefsManager.UpdateHunterProfile(_profile.Clone());
        _isDirty = false;
        SaveButton.Disabled = true;
        OnProfileChanged?.Invoke();
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (disposing)
            _entityManager.DeleteEntity(_previewDummy);
    }
}
