using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;

namespace Content.Client._Stories.Hunter.Profiles.UI;

[GenerateTypedNameReferences]
public sealed partial class SpritePickerButton : ContainerButton
{
    [Dependency]
    private readonly IEntityManager _entityManager = default!;

    [Dependency]
    private readonly IPrototypeManager _prototypeManager = default!;

    private EntityUid? _dummy;

    public SpritePickerButton(EntProtoId prototype)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Prototype = prototype;

        ToggleMode = true;

        OnToggled += _ => UpdateHighlight();

        if (_prototypeManager.TryIndex(prototype, out var proto))
        {
            ToolTip = proto.Name;

            _dummy = _entityManager.SpawnEntity(prototype, MapCoordinates.Nullspace);
            SpriteView.SetEntity(_dummy);
        }

        UpdateHighlight();
    }

    public EntProtoId Prototype { get; }

    public void UpdateHighlight()
    {
        if (Highlight != null)
            Highlight.Visible = Pressed;
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing && _dummy.HasValue)
        {
            _entityManager.DeleteEntity(_dummy.Value);
            _dummy = null;
        }

        base.Dispose(disposing);
    }
}
