using System.Linq;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Stories.Hunter.Profiles.UI;

[GenerateTypedNameReferences]
public sealed partial class SpritePicker : ScrollContainer
{
    private readonly List<SpritePickerButton> _buttons = new();

    public SpritePicker()
    {
        RobustXamlLoader.Load(this);
    }

    public event Action<EntProtoId>? OnSelectionChanged;

    public void Populate(IEnumerable<EntProtoId> prototypes)
    {
        Container.DisposeAllChildren();
        _buttons.Clear();

        var sortedProtos = prototypes.OrderBy(p => p.Id).ToList();

        foreach (var proto in sortedProtos)
        {
            var button = new SpritePickerButton(proto);

            button.OnPressed += _ =>
            {
                OnSelectionChanged?.Invoke(proto);

                SetSelected(proto);
            };

            Container.AddChild(button);
            _buttons.Add(button);
        }
    }

    public void SetSelected(EntProtoId prototype)
    {
        foreach (var button in _buttons)
        {
            var shouldBePressed = button.Prototype == prototype;

            if (button.Pressed != shouldBePressed)
                button.Pressed = shouldBePressed;

            button.UpdateHighlight();
        }
    }
}
