- type: rank
  id: RMCRankWeYaJuniorExecutive
  name: Младший Руководитель
  prefix: Мл. Рук.

- type: rank
  id: RMCRankWeYaExecutive
  name: Руководитель
  prefix: Рук.

- type: rank
  id: RMCRankWeYaSeniorExecutive
  name: Senior Руководитель
  prefix: Ст. Рук.

- type: rank
  id: RMCRankWeYaExecutiveSpecialist
  name: Исполнительный Специалист
  prefix: Исп. Спц.
  paygrade: ВЯС5

- type: rank
  id: RMCRankWeYaExecutiveSupervisor
  name: Исполнительный Супервайзер
  prefix: Исп. Спвайз.
  paygrade: ВЯС6

- type: rank
  id: RMCRankWeYaAssistantManager
  name: Ассистента Менеджера
  prefix: Аст. Мндж.

- type: rank
  id: RMCRankWeYaDivisionManager
  name: Менеджер Подразделения
  prefix: Мндж. Пдрзд.

- type: rank
  id: RMCRankWeYaChiefExecutive
  name: Главный Руководитель
  prefix: Глав. Рук.

- type: rank
  id: RMCRankWeYaDeputyDirector
  name: Заместитель Директора
  prefix: Зам. Директор

- type: rank
  id: RMCRankWeYaDirector
  name: Директор
  prefix: Директор

# Lawyers
- type: rank
  id: RMCRankWeYaLegalSpecialist
  name: Юридический Специалист
  prefix: Юр Спц.

- type: rank
  id: RMCRankWeYaLegalSupervisor
  name: Юридический Супервайзер
  prefix: Юр Спвайз.
