using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Client._RMC14;

namespace Content.Client._Stories.Requisitions;

[GenerateTypedNameReferences]
public sealed partial class VehicleRequisitionsOrderButton : BoxContainer
{
    public VehicleRequisitionsOrderButton()
    {
        RobustXamlLoader.Load(this);
        Button.AddStyleClass(CMStyleClasses.CMLabelAlignLeft);
        Button.Label.AddStyleClass(CMStyleClasses.CMLabelAlignLeft);
    }
}
