using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Stories.Requisitions;

[GenerateTypedNameReferences]
public sealed partial class VehicleRequisitionsWindow : DefaultWindow
{
    public VehicleRequisitionsWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
